[AUT-2963] Add possibility to exec acceptance tests against k8s deployed acp
cloudentity/acp-on-k8s pull request #13
Opened 2021-06-18 13:00 UTC by lgonczarik

Add possibility to exec acceptance tests against k8s deployed acp

2021-06-18 13:03 UTC, mzerko-cloudentity approved these changes

2021-06-18 13:03 UTC, mzerko-cloudentity commented on tests/acceptance/docker/docker-compose.yaml
> +    name: chrome_vpcbr
Maybe it can have the same name as named above

2021-06-18 13:03 UTC, mzerko-cloudentity commented on tests/acceptance/docker/docker-compose.yaml
> +        - subnet: 10.160.0.0/16
Maybe we can make subnet smaller? Not sure if it would change anything

2021-06-18 13:11 UTC, lgonczarik commented on tests/acceptance/docker/docker-compose.yaml
> +        - subnet: 10.160.0.0/16
Ok, I'll change this to /24

2021-06-18 13:21 UTC, lgonczarik commented on tests/acceptance/docker/docker-compose.yaml
> +    name: chrome_vpcbr
Changed to chromebr

2021-06-18 13:32 UTC, plandzwojczak-cloudentity approved these changes

2021-06-21 08:07 UTC, mbilski requested changes
We don't want to run any acceptance tests here. 
We should only run smoke-tests and they should be part of our github actions pipeline https://github.com/cloudentity/acp-on-k8s/blob/master/.github/workflows/test.yaml
There should be no need to define pom.xml

2021-07-23 06:17 UTC, closed without merging