Update README
cloudentity/acp-on-k8s pull request #31
Opened 2021-12-23 12:32 UTC by pdzieniszewski1

## Jira task - PUT_JIRA_LINK_HERE

## BREAKING CHANGE - remove this line if your code doesn't introduce a breaking change

## Description

## Type of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Tests (extending the test suite)
- [ ] Refactor (internal improvement that doesn't change product functionality)
- [ ] Other (if none of the other choices apply)

## Implementation details

## Screenshots (if appropriate):

2021-12-23 13:52 UTC, artursmolarek requested changes

2021-12-23 13:52 UTC, artursmolarek commented on README.md
> +1. Copy `kind` binary to `/usr/local/bin` directory with permission to execute.
Please add the command that should be executed, so we can just copy&paste it.

2021-12-27 07:49 UTC, mbilski requested changes

2021-12-27 07:49 UTC, mbilski commented on README.md
> +1. Copy `kind` binary to `/usr/local/bin` directory with permission to execute.
The readme file should work for all the operating systems.
I don't think `copy kind to /usr/local/bind` applies to every OS.
I would rather redirect the user to the kind installation guide instead.

2021-12-29 08:34 UTC, pdzieniszewski1 commented on README.md
> +1. Copy `kind` binary to `/usr/local/bin` directory with permission to execute.
Do you use macOS? Can you confirm that i.e. brew installing kind globally?

2021-12-29 08:50 UTC, pdzieniszewski1 commented on README.md
> +1. Copy `kind` binary to `/usr/local/bin` directory with permission to execute.
I have added this note because inside makefile we run many times kind command globally and the official instruction provides only description for local install so I got error during `make all`

2021-12-29 10:19 UTC, pdzieniszewski1 commented on README.md
> +1. Copy `kind` binary to `/usr/local/bin` directory with permission to execute.
Checked with @artursmolarek

2021-12-29 10:27 UTC, artursmolarek approved these changes

2021-12-30 08:10 UTC, pdzieniszewski1 commented on README.md
> +1. Copy `kind` binary to `/usr/local/bin` directory with permission to execute.
Done

2021-12-30 09:08 UTC, ppodbielski-cloudentity approved these changes

2022-01-04 08:33 UTC, mbilski approved these changes

2022-01-04 11:38 UTC, merged