[AUT-5188] single command to setup graphql demo
cloudentity/acp-on-k8s pull request #34
Opened 2022-02-02 08:33 UTC by morus12

## Jira task - [PUT_JIRA_LINK_HERE](https://cloudentity.atlassian.net/browse/AUT-5188)

## Description

Added `make graphql-demo` that sets up GraphQL demo with:
- installed ACP
- installed Istio and Istio Authorizer
- installed Countries GraphQL service

![Screenshot 2022-02-02 at 09-28-57 Playground - http countries ingress k8s 9080 ](https://user-images.githubusercontent.com/2753312/152119369-328e83d2-60c5-4c01-a9fb-d21ed53beec0.png)

## Type of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Tests (extending the test suite)
- [ ] Refactor (internal improvement that doesn't change product functionality)
- [x] Other (if none of the other choices apply)

2022-02-02 08:45 UTC, holowinski requested changes

2022-02-02 08:45 UTC, holowinski commented on examples/graphql-demo/parse-body.yaml
> +apiVersion: networking.istio.io/v1alpha3
There's a new extension to `istio-authorizer` helm chart which does this part.

Have a look at https://github.com/cloudentity/acp-helm-charts/pull/137
It probably makes sense to use this when the PR gets merged.

2022-02-02 08:56 UTC, ikawalec requested changes

2022-02-02 08:56 UTC, ikawalec commented on examples/graphql-demo/istio-configmap.py
> +yaml.safe_dump(y, sys.stdout)
Potentially, you could use istio operator: https://github.com/cloudentity/acp-saas/blob/master/apps/base/istio-tests/istio_operator.yaml#L28 to install istio and apply configmap changes.

2022-02-02 08:56 UTC, ikawalec commented on values/istio-authorizer.yaml
> +  DO_NOT_FAIL_ON_NON_MATCHING_REQUESTS: "true"
why this is required?

2022-02-03 12:00 UTC, morus12 commented on values/istio-authorizer.yaml
> +  DO_NOT_FAIL_ON_NON_MATCHING_REQUESTS: "true"
Countries demo exposes UI for querying GraphQL API. 
Istio Authorizer doesn't support mixed mode (GraphQL + REST) for a single service.

2022-02-22 09:27 UTC, ikawalec commented on values/istio-authorizer-graphql.yaml
> +    do_not_fail_on_non_matching_requests: true
FYI with 2.x release, this will be changed to:

```
enforcement:
  allowUnknown: true
```

2022-02-22 09:27 UTC, ikawalec approved these changes

2022-03-07 08:28 UTC, holowinski approved these changes

2022-03-08 05:19 UTC, merged